In [27]:
with open('./german.data-numeric','r') as f:
    data = f.readlines()

In [13]:
import numpy as np

In [28]:
for i in range(len(data)):
    newd = np.array(data[i].strip().split(' '))
    data[i] = newd[newd!=''].astype(np.int)
#     break

In [29]:
data = np.vstack(data)

In [30]:
print(data.shape)

(1000, 25)


In [31]:
print(data)

[[ 1  6  4 ...  0  1  1]
 [ 2 48  2 ...  0  1  2]
 [ 4 12  4 ...  1  0  1]
 ...
 [ 4 12  2 ...  0  1  1]
 [ 1 45  2 ...  0  1  2]
 [ 2 45  4 ...  0  1  1]]
